# Site settings
title: Deacon Wellman
description: My Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ewan McDonnell
user_description: I graduated in Computer Science 2017. My major project was a web app using Sinatra and utilising technologies such as git, SQL databases and Bootstrap 4.
user_title: Postal Delivery Officer, Former Project Officer, Advertising Consultant and Corporate Concierge.
email: legoflamb79@gmail.com
github_username:  MrEwan79


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
